PUT http://localhost:8080/events/1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MTgxMTEyMTUsInVzZXJfaWQiOjF9.7nAzEVYzp8Q6GkMzlj3PO7dnhdtobO-DeyIpvUJBgMA

{
  "name": "Updated Test Event",
  "description": "An updated test event",
  "location": "An updated test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}